### ISSUE TITLE
[FEATURE] Improvements to the GuardDuty Solution

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-security-reference-architecture-examples#107]
I've been reviewing the configurations of GuardDuty following a base deployment on top of Control Tower and have noticed that there is no configuration option within the Current Automation to Enable EKS Audit Logs or the New Malware Protection option.

Would be extremely useful for these aspects to be added in longer term.

Thanks in Advance.

**Comment by andywick-aws** [comment]
Thank you for the feature request @AdamDivall. We will add these 2 items to our backlog.

**Comment by AdamDivall** [comment]
@andywick-aws Another thing in relation to the EKS Audit Logs being enabled would be to be able to integrate it with Amazon Detective as per the [Blog Post](https://aws.amazon.com/blogs/aws/amazon-detective-supports-kubernetes-workloads-on-amazon-eks-for-security-investigations/)

**Comment by liamschn** [comment]
Hello @AdamDivall these plus other guardduty features have been added.  See https://github.com/aws-samples/aws-security-reference-architecture-examples/commit/97e9968a2e6011f6919c02083f6220bde89c802e
