### ISSUE TITLE
[FEATURE] Add Amazon Inspector

### ISSUE THREAD

**Issue by EmpoweringSecurity** [aws-samples/aws-security-reference-architecture-examples#109]
### Is your feature request related to a problem? Please describe

In alignment with the updated toolsets in SRA guidance, it would be extremely useful for Amazon Inspector example solution to be created and shared in this repo. 

### Describe the solution you'd like

A example solution that deploys Amazon Inspector, including delegating the administrator and the option to automatically enable scanning for all member accounts.

Thank you in advance.

**Comment by liamschn** [comment]
Hello- @EmpoweringSecurity,  I am pleased to let you know that we indeed now have a solution for Amazon Inspector, including delegating the administrator and the option to automatically enable scanning for all member accounts.  It can be found here: https://github.com/aws-samples/aws-security-reference-architecture-examples/tree/main/aws_sra_examples/solutions/inspector/inspector_org

-Liam
