### ISSUE TITLE
[FEATURE] Automated Patching with AWS Systems Manager Patch Manager

### ISSUE THREAD

**Issue by EmpoweringSecurity** [aws-samples/aws-security-reference-architecture-examples#110]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Is your feature request related to a problem? Please describe

In alignment with the updated toolsets in SRA guidance, it would be extremely useful for automated patching example solution to be created and shared in this repo using AWS Systems Manager Patch Manager. 

### Describe the solution you'd like

A example solution that deploys AWS Systems Manager Patch Manager with a patch baseline across the appropriate OUs with configurable key variables.

Thank you in advance.

**Comment by mlfulleraws** [comment]
UpVote Here
