### ISSUE TITLE
[BUG] Security Hub - Disabling All Standards

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-security-reference-architecture-examples#129]
### Describe the bug

I've a scenario where a Customer wishes to disable all Standards that Security Hub offers and instead leverage prowler scans findings being imported into Security Hub and therefore reducing the Cost of AWS Config in the process.

When disabling all the appropriate standards via the CFN Parameters using as an Input for CfCT to deploy to the AWS Org, we're seeing that in the Management Account all Standards are disabled in all regions, however in every other Member Account in the AWS Org all standards are disabled with the exception of CIS 1.2 which is enabled in all AWS Regions (that are governed by Control Tower).  

### To Reproduce

Pass in the following parameter settings via a json file in the manifest.yaml:
    {
        "ParameterKey": "pEnableCISStandard",
        "ParameterValue": "false"
    },
    {
        "ParameterKey": "pEnablePCIStandard",
        "ParameterValue": "false"
    },
    {
        "ParameterKey": "pEnableSecurityBestPracticesStandard",
        "ParameterValue": "false"
    }

Utilise the sra-securityhub-org-main-ssm.yaml in the manifest.yaml as the CFN Template
Commit and wait for the CFCT Pipeline to complete.

### Expected behavior

Security Hub Standard in all accounts should reflect what was provided via CloudFormation Parameters.

**Comment by andywick-aws** [comment]
Make sure to set the pCISStandardVersion to 1.2.0 as the latest template sets 1.4.0 as the default. Once this is set you will need to run the code 2 times. Once with pEnableCISStandard = "true" and then pEnableCISStandard = "false". Also, setting the pDisableSecurityHub = "true" will attempt to disable Security Hub in all the member accounts.

**Comment by AdamDivall** [comment]
Thanks @andywick-aws.  That's fixed the issue.
