### ISSUE TITLE
[FEATURE] Add NIST Standard support to Security Hub

### ISSUE THREAD

**Issue by ashmeetp** [aws-samples/aws-security-reference-architecture-examples#133]
In a recent update, Security Hub now natively supports NIST 800-53 Rev5 standard, which eliminates deploying and managing NIST 800-53 Rev5 Config Conformance pack. It'd be nice to have the standard supported in Security Hub so it can be enabled on all a new accounts added to the Organization.

Add any other context or screenshots about the feature request here. e.g. link to a new AWS feature

https://aws.amazon.com/about-aws/whats-new/2023/03/aws-security-hub-support-nist-sp-800-53-rev-5/

**Comment by justin-kontny** [comment]
@ashmeetp Thanks for submitting this issue. We've added this item to our roadmap.

**Comment by justin-kontny** [comment]
Added functionality to Security Hub Solution to support NIST 800-53 Rev5 standard via
https://github.com/aws-samples/aws-security-reference-architecture-examples/pull/134
