### ISSUE TITLE
[BUG] customizations-for-aws-control-tower fails deployment 

### ISSUE THREAD

**Issue by MithilShah** [aws-samples/aws-security-reference-architecture-examples#137]
### Describe the bug

Because of the this [release](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/) yesterday, the CustomControlTowerS3AccessLogsBucket creation in the customizations-for-aws-control-tower.template template of the CfCt stack is failing. 

To get it to work, I had to remove this line from the template
AccessControl: LogDeliveryWrite (line 263)
see this [wiki](https://w.amazon.com/bin/view/S3/Teams/S3Bauhaus/S3UserSecurityRuntime/S3SentinelBPANoACLByDefaultRunbook#HEnablingServerAccessLogging) page for more details. 

The bug has been fixed in https://github.com/aws-solutions/aws-control-tower-customizations/commit/fabefd83d08e2e56731211eff2dcc7f12534d06e

### Deployment Environment (please complete the following information)

- Deployment Framework [e.g. Customizations for Control Tower and CloudFormation StackSets]:
- Deployment Framework Version [e.g. 1.0, 2.0]:

**Comment by liamschn** [comment]
Updated cfct template to solve this 
commit: https://github.com/aws-samples/aws-security-reference-architecture-examples/commit/89e4b776b2cf3e79fff973cc82931fc1ec0c6cc4
