### ISSUE TITLE
[BUG] Securityhub Org fails to deploy via CloudFormation

### ISSUE THREAD

**Issue by rknightion** [aws-samples/aws-security-reference-architecture-examples#138]
### Describe the bug

The securityhub org stack fails to deploy the rSecurityHubOrgLambdaCustomResource in our Organization environment.

Am using the default cloudformation template with no changes. 

<img width="721" alt="Screenshot 2023-04-30 at 17 19 36" src="https://user-images.githubusercontent.com/12484127/235364151-a96d93db-0cbd-4c59-b5e4-96c3d57201f9.png">

I cant seem to find anything in cloudtrail with an ERROR tag only a bunch of INFOs from the Lambda function. 

As far as I'm aware all the prerequisites are completed (other SRAs deploy fine). The only potential thing is there was an initial Security Hub setup that was removed & Security Hub disabled prior to attempting to run this stack. 

The latest version of SRA is being used.

**Comment by rknightion** [comment]
Closing as the issue was a lack of delegated administrator for the Audit account

**Comment by rknightion** [comment]
Reopening as despite resolving the issue of a lack of delegated administrator on the Audit account, provisioning still fails. 

In the custom lambda function log group there's lots of log entries like:
`{"timestamp": "2023-04-30 17:16:31,703", "level": "INFO", "location": "sra.all_standards_ready:475", "RequestType": "Create", "StackId": "arn:aws:cloudformation:us-east-1:xxxxxxxxx:stack/sra-securityhub-org-main-ssm-rSecurityHubConfigurationStack-2CXTPFMB1SD1/e849b5f0-e778-11ed-b10c-0afd497892d5", "RequestId": "7f988dd8-e8b3-4beb-a775-c7fee797284b", "LogicalResourceId": "rSecurityHubOrgLambdaCustomResource", "aws_request_id": "96fad779-df36-4ae9-bd7f-f39f1328788d", "message": "Waiting 20 seconds before checking if standards are in READY status. 3 of 10"}`

Counting up to 10 then starting again from 0.

In the earlier logs there is no indication of any error and eventually the function times out:

```
{"timestamp": "2023-04-30 17:20:18,821", "level": "ERROR", "location": "crhelper.resource_helper._timeout:211", "RequestType": "Create", "StackId": "arn:aws:cloudformation:us-east-1:xxxxxx:stack/sra-securityhub-org-main-ssm-rSecurityHubConfigurationStack-2CXTPFMB1SD1/e849b5f0-e778-11ed-b10c-0afd497892d5", "RequestId": "7f988dd8-e8b3-4beb-a775-c7fee797284b", "LogicalResourceId": "rSecurityHubOrgLambdaCustomResource", "aws_request_id": "96fad779-df36-4ae9-bd7f-f39f1328788d", "message": "Execution is about to time out, sending failure message"}
{"timestamp": "2023-04-30 17:20:18,916", "level": "INFO", "location": "crhelper.utils._send_response:44", "RequestType": "Create", "StackId": "arn:aws:cloudformation:us-east-1:xxxxxx:stack/sra-securityhub-org-main-ssm-rSecurityHubConfigurationStack-2CXTPFMB1SD1/e849b5f0-e778-11ed-b10c-0afd497892d5", "RequestId": "7f988dd8-e8b3-4beb-a775-c7fee797284b", "LogicalResourceId": "rSecurityHubOrgLambdaCustomResource", "aws_request_id": "96fad779-df36-4ae9-bd7f-f39f1328788d", "message": "CloudFormation returned status code: OK"}
```

**Comment by liamschn** [comment]
Hello @rknightion this issue is confirmed on our end and this is a high priority for us.  We have been looking at it for a few days now.  We have some code we are testing as a workaround.  I saw the issue in ap-northeast-1 and ap-northeast-2.  The service itself was reporting “INCOMPLETE” for the standards being ready which made the retries continue to happen.  After manually disabling the standard and re-enabling in the impacted region, then things worked.  It doesn’t appear to happen in all regions.

The service team (Security Hub) reported that it may be due to some updates happening in the regions.

The code we are testing for a fix to this may be difficult to validate if the issue is indeed transient.  We will keep you informed.

**Comment by rknightion** [comment]
Thanks @liamschn that's good to know the team are already on it. 
For reference, I'm only deploying in us-east-1, eu-west-1 & eu-central-1.

I will give disabling the standards a try

**Comment by liamschn** [comment]
Thank you for that info, super helpful to know the regions you are deploying in!

**Comment by rknightion** [comment]
Disabling all the standards did the trick & its all deployed now. Will close this as my instance is working well. Thanks!

**Comment by liamschn** [comment]
re-opening because there is some code we have to resolve this without a workaround.

**Comment by liamschn** [comment]
re-opening because there is some code we have to resolve this without a workaround.

**Comment by rknightion** [comment]
Is there an update on this at all? - Keen to be able to enable the standards via cloudformation as without it any changes get undone :)
