### ISSUE TITLE
[BUG]  Parameters AllowedPattern causes error with the default despite of the value matches

### ISSUE THREAD

**Issue by hori1108** [aws-samples/aws-security-reference-architecture-examples#160]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Describe the bug

During deployment of the SRA, the sra-quick-setup-ssm Stack fails to create the 2 parameters 

- pBucketNamePrefix

- pMacieOrgDeliveryKeyAlias

I used default parameters and they looked match allowed patterns, but it was not completed.
It was succeded after comment out AllowedPattern from yaml.

### To Reproduce

According to READ.ME, I deploied sra-quick-setup-ssm with CloudFormation
https://github.com/aws-samples/aws-security-reference-architecture-examples/blob/main/aws_sra_examples/quick_setup/README.md

**Comment by liamschn** [comment]
We will take a look at this!  thank you for reporting.

**Comment by mlfulleraws** [comment]
Thank you for reporting this issue, quick setup is deprecated. Please leverage Easy Setup.
