### ISSUE TITLE
[Guidance] Stack_set deployment to OUs not deploying

### ISSUE THREAD

**Issue by sbrown-tecracer** [aws-samples/aws-security-reference-architecture-examples#164]
Stack_set deployment to OUs using the CustomControlTower-sra-account-alternate-contacts-main-ssm not deploying

Deplying stack_set to OU's under an CfCT einvornment giving following error - 

Error:
`ResourceLogicalId:rAccountAlternateContactsConfigurationIAMRoleStackSet, ResourceType:AWS::CloudFormation::StackSet, ResourceStatusReason:Resource handler returned message: "You must be the management account or delegated admin account of an organization before operating a SERVICE_MANAGED stack set (Service: CloudFormation, Status Code: 400, Request ID: 2933e127-b71d-4937-b63a-29ff1e3e1c39)" (RequestToken: e8857ad8-3d1b-d8d9-6c96-9fcf734eb13f, HandlerErrorCode: InvalidRequest).`

Could someone point me to the required Role?
Assuming this needs updating?

### Environment

CfCT2.6.0/SRA1.3/Solution-AlteranteContacts1.1
![image](https://github.com/aws-samples/aws-security-reference-architecture-examples/assets/41792962/9e0ebe15-c5e8-4350-83d4-4404a04cdd17)

### Other information

![image](https://github.com/aws-samples/aws-security-reference-architecture-examples/assets/41792962/f54374aa-e447-404c-92a5-3400e3e0ae36)

**Comment by liamschn** [comment]
Hi @sbrown-tecracer,
Are you by chance specifying `organizational_units` as the `deployment_targets` in your manifest file instead of `accounts`?
If so, that is probably the source of your issue.  You must specify the management account under `accounts` to deploy SRA solutions via CfCT (it will not deploy any other way).

**Comment by sbrown-tecracer** [comment]
Hi @liamschn ,
Perfect, thankyou.

As this is a "big bang" approach, omitting accounts / OU's to be deployed would need to be defined in the StackSets themselves?

**Comment by liamschn** [comment]
Closing; to recap, deploy via CFCT using the management account in the deployment target.  OUs is a feature request we are considering (and of course how to do this).
