### ISSUE TITLE
[Guidance] Ran the easy_setup but failed due to insufficient permission of IAM role"sra-codebuild-role" 

### ISSUE THREAD

**Issue by fryce** [aws-samples/aws-security-reference-architecture-examples#170]
### The Question

Using easy_setup to deploy Guardduty solution, the CodeBuild project of initiated by SRA stopped with failure with the message saying **sra-codebuild-role is not existing or not having enough permissions**.  -- Checked the IAM console, during the CodeBuild process, the role was created so seems it's insufficient permission problem.

Anyone faced same error before or any idea what steps might be missing from me?

### Environment

(All the steps were executed in management account)

1. New AWS org, installed the [CfCT](https://github.com/aws-solutions/aws-control-tower-customizations/tree/main) resources (the pipeline services)
2. Uploaded the easy_setup yaml file to the CfCT CodeCommit repo
3. Updated the manifest file in the CfCT CodeCommit repo
4. Fulfilled the [pre-req](https://github.com/aws-samples/aws-security-reference-architecture-examples/blob/main/aws_sra_examples/easy_setup/README.md) 
5. Turned on the GuardDuty solution by editing the parameter in manifest file
6. Committed and pushed the changes to CodeCommit
7. When deploying, the error occurred

<img width="1352" alt="Screenshot-codebuild-error" src="https://github.com/aws-samples/aws-security-reference-architecture-examples/assets/7770653/927b8f8a-7966-4cdf-a4e8-908eb9c65de8">

**Comment by liamschn** [comment]
Closing due to age.  Was unable to recreate this issue.  Please reach out if still having issues.
