### ISSUE TITLE
[FEATURE] Add Amazon Security Lake to the SRA

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-security-reference-architecture-examples#188]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Describe the solution you'd like

I'd like to see Amazon Security Lake added to the SRA as an additional Solution as per [here](https://docs.aws.amazon.com/prescriptive-guidance/latest/security-reference-architecture/security-tooling.html).  

Additionally, providing recommendations of either native AWS Tooling (OpenSearch, Athena, QuickSight etc..) or 3rd Party Tools such as Cribl, Splunk etc for then either establishing your home grown or 3rd party SIEM.

**Comment by mlfulleraws** [comment]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by IevIe** [comment]
launched with merge #261
