### ISSUE TITLE
[BUG] Invalid Values in CfCT Parameters Files for Security Hub

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-security-reference-architecture-examples#189]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Describe the bug

Both the parameters files in the repository for Security Hub (solutions/securityhub/securityhub_org/customizations_for_aws_control_tower/parameters) contain invalid values for what is in sra-securityhub-org-main-ssm.yaml and sra-securityhub-org-main.yaml.

Specifically the parameters files have pSRASolutionVersion being set to v1.3 whilst the CFN templates have allowed values set to v1.5

**Comment by mlfulleraws** [comment]
Thank you for reporting the issues, we have tested the issue and could not replicate.
