### ISSUE TITLE
[BUG] CFCT fails to validate due to issue with Values in Alternate Account Contacts Parameter File

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-security-reference-architecture-examples#190]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Describe the bug

CFCT fails to successfully complete the Pipeline due to the value for pComplianceFrequency not being in Quotes as it complains that the value is an int as opposed to a string

### To Reproduce

Copy the current parameters file for the alternate account contacts and use that to pass in the values to the CFN Template.

### Expected behavior

Pipeline should complete successfully.  

The fix is to update the repo and ensure all parameter files values are in quotes.

**Comment by mlfulleraws** [comment]
Tested and could not replicate - specified parameter is Type: Number and deployment worked
