### ISSUE TITLE
[FEATURE]  AWS-Nuke addition per OU

### ISSUE THREAD

**Issue by sbrown-tecracer** [aws-samples/aws-security-reference-architecture-examples#206]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Is your feature request related to a problem? Please describe

Problem is the rising cost of resources not fully managed within accounts.
Reducing this using AWS-Nuke addresses the cost issues and management failures

### Describe the solution you'd like

Manage Account Services based on Tags and of course deployed to specific OU's in an Orga using AWS-Nuke

### Describe alternatives you've considered

None found thus far

### Additional context

Link to the docs: https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/automate-deletion-of-aws-resources-by-using-aws-nuke.html

**Comment by mlfulleraws** [comment]
Thank you for reporting the issues, this is out of scope for the AWS SRA
