### ISSUE TITLE
[BUG] Error attempting to add CloudTrail solution with easy setup

### ISSUE THREAD

**Issue by wagnerone** [aws-samples/aws-security-reference-architecture-examples#209]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Describe the bug

After successfully applying the easy setup with limited solutions enabled, I subsequently adding a few solutions one-by-one with change sets. Adding CloudTrail solution with default settings fails to apply with error in change set

`Parameter pCloudTrailS3BucketName failed to satisfy constraint: S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).`

### To Reproduce

1. Apply `sra-easy-setup.yaml` with limited solution set (DeployEC2DefaultEBSEncryptionSolution, DeployIAMPasswordPolicySolution). 
2. Create change set and enable CloudTrail solution with all defaults
3. See error

### Expected behavior

CloudTrail solution should be enabled with default values.

### Screenshots

![Capto_Capture 2024-02-28_08-50-07_](https://github.com/aws-samples/aws-security-reference-architecture-examples/assets/6237466/4043dc3c-9da3-433b-81d6-3c2d5a408491)

### Deployment Environment (please complete the following information)

- Deployment Framework [e.g. Customizations for Control Tower and CloudFormation StackSets]: Easy Setup
- Deployment Framework Version [e.g. 1.0, 2.0]: 

`main` `55557a4ad16ddab7ca03f403fda4a88412f652f8`

**Comment by mlfulleraws** [comment]
Thank you for reporting the issues, this is tech debt that we acknowledge, the SRA code library deployment via Cloudformation ChangeSets fails
