### ISSUE TITLE
[FEATURE]  Possibility to deactivate creation of SNS Topics for every Service

### ISSUE THREAD

**Issue by janahockenberger** [aws-samples/aws-security-reference-architecture-examples#221]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
 
### Describe the solution you'd like

Currently for every Security Service a separate SNS Topic is created automatically. Please add the possibility f.e. with setting a parameter to deactivate the creation of the SNS Topics if it's not necessary. In our case we don't need them and want to reduce the overload of unused resources. 

Also if I got it right the SNS topics are created in the org account. Wouldn't it make more sense to create them in the Account where the specific feature is enabled? F.e. to create the SNS Topic for Inspector in the audit account to have the possibility of getting notified for the events of all accounts?

**Comment by mlfulleraws** [comment]
Thank you for reporting the issues, we have tested the issue and could not replicate. The SNS topic for deployment is not an optional component.
