### ISSUE TITLE
AWS Systems Manager Patch Management Solution

### ISSUE THREAD

**Issue by mlfulleraws** [aws-samples/aws-security-reference-architecture-examples#244]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
 
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mk-amz** [comment]
@liamschn @justin-kontny This is ready for review.

**Comment by mk-amz** [comment]
https://github.com/aws-samples/aws-security-reference-architecture-examples/pull/210

**Comment by mlfulleraws** [comment]
Launched Aug 23rd, 2024: https://github.com/aws-samples/aws-security-reference-architecture-examples/tree/main/aws_sra_examples/solutions/patch_mgmt/patch_mgmt_org 

Thank you Contributors and Owners: 

Contributors:
Miclain Keffeler, Security Consultant, AWS WWCO ProServe
Rob Troke, Sr. Security Consultant, AWS WWCO ProServe

AWS SRA Members:
Ievgeniia Iermenko, Security Engineer, AWS GSS Privacy, Security, Assurance
Liam Schneider, Senior Security Engineer, AWS GSS Privacy, Security, Assurance
Justin Kontny, Senior Security Engineer, AWS GSS Privacy, Security, Assurance

**Comment by IevIe** [comment]
Launched on Aug 23rd, 2024

**Comment by IevIe** [comment]
Launched Aug 23rd, 2024
