### ISSUE TITLE
[BUG] syntax error in package-lambda.sh

### ISSUE THREAD

**Issue by Schizamp** [aws-samples/aws-security-reference-architecture-examples#63]
[ec2-user@ip-10-129-28-246 ~]$ python package-lambda.sh -h
  File "package-lambda.sh", line 20
    usage="$(basename "$0") [-h] <--file_name s> [--bucket s] <--src_folder s> ---script to package lambda zip and upload to s3
                       ^
SyntaxError: invalid syntax

**Comment by andywick-aws** [comment]
Can you provide what is flagging the syntax error? Make sure the entire usage statement is included. 
`usage="$(basename "$0") [-h] <--file_name s> [--bucket s] <--src_folder s> ---script to package lambda zip and upload to s3

where:
    -h  show this help text
    --file_name  <required> Lambda zip file
    --bucket  [optional] S3 bucket name for lambda source
    --src_dir <required> Lambda source directory"`

**Comment by andywick-aws** [comment]
I'm unable to reproduce any errors when running the package-lambda.sh script on a Mac terminal or Windows (using git bash). If you are still having issues, please open another issue with details on how you are getting the "SyntaxError".
