### ISSUE TITLE
[BUG] - CF Templates from Examples fail if Region doesn't support arm Lambda Functions

### ISSUE THREAD

**Issue by alexandreags** [aws-samples/aws-security-reference-architecture-examples#89]
### Describe the bug

CF Templates fail if Region doest support arm Lambda Functions

### To Reproduce

1. Apply any SRA Example in Regions that doesnt support arm Lambda (sa-east-1), for example.

### Expected behavior

Stackset fail with architecture unsupported error

### Recomendation

Update the CF to check if Region has supported arm lambda.

**Comment by tekdj7** [comment]
Thank you for filing the issue. We will review which regions support Graviton2 (arm64), and address accordingly.
